name: My Selenium 2

on:
  workflow_dispatch:
  schedule:
    #- cron: '0 */6 * * *' 
    - cron: '0 1,7,13,19 * * *'

jobs:
  youtube_bot:
    continue-on-error: true
    strategy:
      matrix:
        email:
          # 28/2 7day
          - 'lyhuutanmswxhjn3dfd3@rotitk.us'
          - 'vuongtamthiencta3hx5ftpwc@rotitk.us'
          - 'tranthituyet1mthh90f273l@rotitk.us'
          - 'banhmailienliubmb4igf17@rotitk.us'
          - 'lelamtruongjoxo89qmxsc7@rotitk.us'
          - 'nguyenthanhtinsdea2jqbvy9p@rotitk.us'
          - 'thaobaochauoeyv2j6v7ytc@rotitk.us'
          - 'nguyenlehonggainputuu0w05j7@rotitk.us'
          - 'nghiemngocthienyydt8jhxv5qq@rotitk.us'
          - 'nguyenthicamnhung3iixkeutfv0w@rotitk.us'
          - 'vanmanhtuongn682aueavpp1@rotitk.us'
          - 'tranmyngocvga3xeyo9ctq@rotitk.us'
          - 'lamducphue1ar825qv1bu@rotitk.us'
          - 'banhminhdatw51b2ucswlay@rotitk.us'
          - 'doanquynhgiangivudbs97x7mh@rotitk.us'
          - 'vothiennuongmc3s81euydy2@rotitk.us'
          - 'trinhkimtuyetbtdkjnhjkhi9@rotitk.us'
          - 'nguyenmaithaon733js9b4vzc@rotitk.us'
          - 'duongtanthanh90v1cjdtkyzk@rotitk.us'
          - 'hohuytuan3blifh7wuqme@rotitk.us'
        #email: ['nguyenthuhuonghpwr9uhh7501@rotitk.us', 'lemykieue93yotx2fj6f@rotitk.us', 'nguyenmongnhif74lkeeuz7dc@rotitk.us','mackimtuyenfbuyscf654ei@rotitk.us','nguyenbaolamrsf3t8fjfdih@dfphayy.us'] 
    runs-on: windows-latest  # Chạy trên hệ điều hành Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium chromedriver_autoinstaller undetected-chromedriver fake-useragent

      - name: Run Selenium script
        run: |
          # Truyền email từ matrix vào Python script
          python my_selenium2.py --email ${{ matrix.email }} --password ${{ secrets.PASSWORD }}

      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots-${{ matrix.email }}
          path: screenshots/
